#PBS -q class
#PBS -l nodes=1:m2090
#PBS -l walltime=00:10:00
#PBS -N cuda

# Changes to the directory we were in when we
# submit the job:

cd $PBS_O_WORKDIR

# Runs a bunch of standard command-line
# utilities, just as an example:

echo "Script began:" `date`
echo "Node:" `hostname`
echo "Current directory: ${PWD}"

echo ""
echo "=== Running BFS ... ==="
./bfs 10240

echo ""
echo "=== Done! ==="

# eof
